# Kubernetes Secret Template for Slack Credentials
# DO NOT commit actual secrets to git!
#
# This file is a template. Create secrets using one of these methods:
#
# Method 1: Using Makefile (Recommended)
#   make secret SLACK_TOKEN=xoxb-your-actual-token-here
#
# Method 2: Using kubectl directly
#   kubectl create secret generic slack-credentials \
#     --from-literal=slack-bot-token="xoxb-your-actual-token-here" \
#     --namespace=kube-bench
#
# Method 3: Using the create-secret.sh script
#   ./scripts/create-secret.sh
#
# The secret will be created dynamically and never stored in git.

apiVersion: v1
kind: Secret
metadata:
  name: slack-credentials
  namespace: kube-bench
type: Opaque
stringData:
  slack-bot-token: "REPLACE_WITH_YOUR_TOKEN"  # This is just a placeholder
