{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-bench-slack.serviceAccountName" . }}
  namespace: {{ include "kube-bench-slack.namespace" . }}
  labels:
    {{- include "kube-bench-slack.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-bench-slack.clusterRoleName" . }}
  labels:
    {{- include "kube-bench-slack.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services", "endpoints", "persistentvolumes"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: ["daemonsets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-bench-slack.clusterRoleBindingName" . }}
  labels:
    {{- include "kube-bench-slack.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-bench-slack.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-bench-slack.serviceAccountName" . }}
  namespace: {{ include "kube-bench-slack.namespace" . }}
{{- end }}
