{{- if .Values.slack.token }}
{{- if kindIs "string" .Values.slack.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-bench-slack.secretName" . }}
  namespace: {{ include "kube-bench-slack.namespace" . }}
  labels:
    {{- include "kube-bench-slack.labels" . | nindent 4 }}
type: Opaque
stringData:
  slack-bot-token: {{ .Values.slack.token | quote }}
{{- end }}
{{- end }}
